### ISSUE TITLE
Default cluster configuration not working.

### ISSUE THREAD

**Issue by lukjel** [vert-x3/vertx-openshift-cartridge#2]
I've created simple demo app for OpenShift. (http://github.com/lzeligowski/vertx3-demo-openshift) 

Without clustering works great, but when I added cluster feature - I've got errors.

Failed to join cluster
com.hazelcast.core.HazelcastException: ServerSocket bind has failed. Hazelcast cannot start! config-port: 5701, latest-port: 15701

As far as I understand I have to configure proper ports for cluster. However in cartridge documentation it's written I have to do something only in case of custom cluster.xml - which is not a case right  here.

Is this my failure - then where should I put cluster.xml file and how should it looks like, or there is a bug (not a feature...)? For sure - documentation should be more clear about this (some example would be the best).

**Comment by cescoffier** [comment]
So several thing.

It seems that the `HAZELCAST_PROXY_PORT` is not injected anymore (this is a change on openshift).

Then, openshift does not support multicast, so at the end you need to provide your own `cluster.xml` file and maintain the member list yourself.

**Comment by lukjel** [comment]
Ok. So - I've got cluster.xml 

Here is the most important part:
    <public-address>ADDRESS:PORT</public-address>
    <port auto-increment="false" port-count="100">5701</port>
    <join>
      <multicast enabled="false">
      </multicast>
      <tcp-ip enabled="true">
        <members>ADDRESS:PORT</members>
      </tcp-ip>

Which address should I put here? and port too?

When I push changes I see something like this:

remote: CLIENT_MESSAGE: Vert.x OPTS:  -Dhttp.port=8080 -Dhttp.address=some_ip1 -Dvertx.cluster.public.host=some_ip2 -Dvertx.cluster.public.port=41588
remote: CLIENT_MESSAGE: Vert.x Cluster parameters : -cluster -cluster-port 9123 -cluster-host some_ip3
remote: CLIENT_MESSAGE: Vert.x Application parameter : 

As I understand - section public-address should looks like:
<public-address>some_ip2:41588</public-address>

and section tcp:
<tcp-ip enabled="true">
        <members>some_ip3:9123</members>
</tcp-ip>

Am I right?

When I finished my example app - maybe you can use it as an example for your project.

**Comment by cescoffier** [comment]
So first I was wrong the `HAZELCAST_PROXY_PORT` is correctly injected (my bad, forgot to create an application with `-s`).

So, get the IP:PORT of the first application's cluster.xml and add it to the member of the second one

At the end you should have something like:

```
<tcp-ip enabled="true">
        <member>${env.OPENSHIFT_VERTX_HAZELCAST_CLUSTER}</member>
        <member>127.6.143.1:5701</member> <!-- replace with the right IP and PORT from the first app -->
</tcp-ip>
```

If you get this to work, I would be really happy to use it as example.

**Comment by lukjel** [comment]
It still looks too dificult for me. 

I want to start on the begining just one instance - so there is no more than one node in my "cluster"... Just for begining.
I looked to my XML file (sorry for bad format of previous post) and I do not know which IP:PORT should I enter to which section.

In  short: during push I see tw different IPs: 
-Dvertx.cluster.public.host
-cluster-host

and ports:
-Dvertx.cluster.public.port
-cluster-port

Which address and port should I enter to section: MEMBER (in TCP-IP), which port should I entered to section PORT, and which IP and port should I enter to section PUBLIC-ADDRESS (if any).

I've tryied to enter these "-D" IP and PORT (cluster.public) to section PUBLIC-ADDRESS,
the other ones to PORT (only port of course) and to MEMBER (-cluster-host and -cluster-port).
Then I've got errors (a part):
Jun 22, 2015 1:03:13 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.164.54.119]:41588 [dev] [3.5] Established socket connection between /127.3.87.129:9123
Jun 22, 2015 1:03:13 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [10.164.54.119]:41588 [dev] [3.5] Established socket connection between /127.3.87.129:20661
Jun 22, 2015 1:03:13 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [10.164.54.119]:41588 [dev] [3.5] Wrong bind request from Address[10.164.54.119]:41588! This node is not requested endpoint: Address[127.3.87.129]:9123
Jun 22, 2015 1:03:13 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.164.54.119]:41588 [dev] [3.5] Connection [Address[127.3.87.129]:9123] lost. Reason: java.io.EOFException[Remote socket closed!]
Jun 22, 2015 1:03:13 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.164.54.119]:41588 [dev] [3.5] Connection [/127.3.87.129:20661] lost. Reason: Socket explicitly closed
Jun 22, 2015 1:03:13 PM com.hazelcast.nio.tcp.ReadHandler
WARNING: [10.164.54.119]:41588 [dev] [3.5] hz._hzInstance_1_dev.IO.thread-in-0 Closing socket to endpoint Address[127.3.87.129]:9123, Cause:java.io.EOFException: Remote socket closed!
Jun 22, 2015 1:03:14 PM com.hazelcast.cluster.impl.TcpIpJoiner
INFO: [10.164.54.119]:41588 [dev] [3.5] 

Members [1] {
    Member [10.164.54.119]:41588 this
}

Jun 22, 2015 1:03:14 PM com.hazelcast.core.LifecycleService
INFO: [10.164.54.119]:41588 [dev] [3.5] Address[10.164.54.119]:41588 is STARTED
2015-06-22 13:03:15,014 DEBUG Using default SystemClock for timestamps
13:03:15.038 [vert.x-eventloop-thread-0] ERROR com.git.ServerStarter -  ######################## error
java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_45]
    at sun.nio.ch.Net.bind(Net.java:437) ~[?:1.8.0_45]
    at sun.nio.ch.Net.bind(Net.java:429) ~[?:1.8.0_45]

**Comment by cescoffier** [comment]
Actually it's much better. 

I've never seen:

```
WARNING: [10.164.54.119]:41588 [dev] [3.5] Wrong bind request from Address[10.164.54.119]:41588! This node is not requested endpoint: Address[127.3.87.129]:9123
```

I'm going to have a look tomorrow morning and come back to you.

**Comment by cescoffier** [comment]
So,

I've made some changed in the cartridge, so no it works with the 'default' cluster.xml. So get the latest cartridge you need to delete and create your application (as I changed the control scripts) and environment variables.

I've also fixed a logging issue.
