### ISSUE TITLE
Cartridge only supporting Java flavor?

### ISSUE THREAD

**Issue by munsuri** [vert-x3/vertx-openshift-cartridge#5]
Hi,

I was wondering why this new cartridge (x3) only expects to run a fat-jar (<a href="https://github.com/vert-x3/vertx-openshift-cartridge/blob/master/bin/control#L115">bin/control#L115</a>) instead of previous polyglot <a href="https://github.com/vert-x/openshift-cartridge/blob/master/bin/control#L167">bin/control#L167</a>
Note: I was trying to use the js example as in previous cartridge.

**Comment by cescoffier** [comment]
You can embed js, groovy and ruby verticles as well is a fat jar. 
Check https://github.com/vert-x3/vertx-examples/tree/master/maven-verticles for examples.

**Comment by munsuri** [comment]
uh, ok, so the _export vertx_app=_ approach is not working anymore with this cartridge then? 

Thanks for that link!

**Comment by cescoffier** [comment]
No, the cartridge just requires that you package your application as a fat jar, whatever the language you use. So, the packaging is much more simple than before (and homogeneous).
